<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>No Eligible</name>
  <uuid>4915ecf9-920e-4521-ae89-9a8e7f339f52</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the amount of 'Eligibility for the Service' equals -1 
then
	set decision to a new Decision_result where
		the amount is the amount of 'Eligibility for the Service' , 
		the msg is the msg of 'Eligibility for the Service' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
