<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>eb632ef7-3d4b-4120-86e9-ef47d03684e4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set tax to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
