<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get_Company_Entrepreneur</name>
  <uuid>426a8f2f-4d84-4111-9acc-0cf539bc2aa7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the amount of 'Eligibility for the Service' is at least 0 and less than 13000
	and entrepreneur
then
	set decision to a new decision_result where
		the amount is 0 , 
		the msg is "تكلفة ترخيص الاستثمار لرائد الأعمال المتعاقد مع جامعة أو حاضنة أعمال " ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
