<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Cost</name>
  <uuid>1e9004f9-fb4f-409e-8bc4-f4a49d99e4e1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[IBM Cloud Pak
profile icon
Filter navigation
Home
Design
Decision Center
Business applications
Decision Server Console
Decision Server Runtime
Business automations
Administration
Business Automations
master
SDAIA-Business-Cal
تسجيل الأعمال التجارية
إصدار ترخيص الاستثمار
Saved at 2:34:29 PM.
Edit
Undo
Redo
No item
Connected to: https://github.com/Solo810/licenseDemo.git
Load changes
Share changes
Deploy
Modeling (8)
Error report (0)
Run (4)
View history
Dependency (1)

Back to the diagram

Get Cost
Type your rule using the list below as reference
Editor hotkeys
Documentation
Errors
1
if
2
    sharePercentage is less than 100 and ProActivity is false and numberOfYears equals 1
3
then
4
    set decision to a new decision_result where
5
        the amount is 12000 , 
6
        the msg is "نسبة الاستثمار السعودي أو الخليجي من رأس المال أقل من 100%" ;
7
else
8
    set decision to a new decision_result where
9
        the amount is -1 , 
10
        the msg is "نسبة الاستثمار السعودي أو الخليجي من رأس المال =100% - للأنشطة المهنية - السنوات > 1 " ;
Search
Inputs (3)
Output (1)
Name
Type
	sharePercentage	number
	numberOfYears	number
	ProActivity	boolean
Eligibility for the Service
Decision node


Details

Logic
Select interaction policy

Filter
Search
Get Cost]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
