<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Cost</name>
  <uuid>1e9004f9-fb4f-409e-8bc4-f4a49d99e4e1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	sharePercentage is less than 100 and ProActivity is false and numberOfYears equals 1
then
	set decision to a new decision_result where
		the amount is 12000 , 
		the msg is "نسبة الاستثمار السعودي أو الخليجي من رأس المال أقل من 100%" ;
else
	set decision to a new decision_result where
		the amount is -1 , 
		the msg is "نسبة الاستثمار السعودي أو الخليجي من رأس المال =100% - للأنشطة المهنية - السنوات > 1 " ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
