<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Company Cost -1</name>
  <uuid>27fba9ac-326f-4944-bc01-7f612526f1e6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the amount of 'Eligibility for the Service' equals -1 
then
	set decision to a new Decision_result where
		the amount is the amount of 'Eligibility for the Service' , 
		the msg is the msg of 'Eligibility for the Service' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
