<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Company Entrepreneur</name>
  <uuid>997f2f64-c10b-4f00-98b8-df17d1bb597e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the amount of 'Eligibility for the Service' is at least 0 and less than 13000
	and entrepreneur
then
	set decision to a new Decision_result where
		the amount is 0 , 
		the msg is "تكلفة ترخيص الاستثمار لرائد الأعمال المتعاقد مع جامعة أو حاضنة أعمال " ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
