<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Eligibility</name>
  <uuid>5aa7c3b0-e3ce-4b51-9256-17816c8303d3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	sharePercentage is less than 100 and ProActivity is false and numberOfYears ≥ 1
then
	set decision to a new decision_result where
		the amount is 12000 , 
		the msg is "نسبة الاستثمار السعودي أو الخليجي من رأس المال أقل من 100%" ;
else
	set decision to a new decision_result where
		the amount is -1 , 
		the msg is "نسبة الاستثمار السعودي أو الخليجي من رأس المال =100% - للأنشطة المهنية - السنوات > 1 " ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
