<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get_Company_Eligibility</name>
  <uuid>d5e8b140-3290-417e-9b64-b18cbb3dc010</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the amount of 'Eligibility for the Service' equals -1 
then
	set decision to a new Decision_result where
		the amount is the amount of 'Eligibility for the Service' , 
		the msg is the msg of 'Eligibility for the Service' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
