<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get_CompanyHQ_Renewal_Cost</name>
  <uuid>af93f6f1-b74e-4f3e-a0f2-991a3c41388b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	classification is "Silver"
	and 'Has HQ in KSA' 
	and renewal_Year is more than 1
    and entrepreneur is false 
then
	set decision to a new Decision_result where
		the amount is 2000 , 
		the msg is "تكلفة تجديد ترخيص الاستثمار المنشأة تعمل بصفتها مقراً إقليمياً في المملكة ومصنفة فضية " ;
else 
	set decision to a new Decision_result where
		the amount is 0 , 
		the msg is "التجديد مجاني ترخيص الاستثمار المنشأة تعمل بصفتها مقراً إقليمياً في المملكة ومصنفة الذهبية والبلاتينية" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
